### ISSUE TITLE
Should Jest be swapped out?

### ISSUE THREAD

**Issue by ianmcnally** [imcnally/react-es6-gulp-playground#1]
When I created this project, I was learning React. When I was learning React, I immersed myself in its ecosystem. This is included Jest, Facebook's layer on top of Jasmine.

After using Jest on a couple projects, I ditched it (see: https://github.com/imcnally/farely-react/commit/b6379851348056d8ba84f5653fca58160db4f273) and replaced it with Mocha, Chai, Sinon and Karma. I found the mock-by-default design of Jest to be more trouble than it was worth.

If I'm making this project a reflection of my technology choices or recommendations, I would move it to mocha & co. But I'm not the only one using it.

So, my open question to anyone using this project is – are you using Jest, or are you just swapping it out for something else? If you're swapping it, what for?

**Comment by subhrm** [comment]
Please switch to mocha & co. 

> I found the mock-by-default design of Jest to be more trouble than it was worth.

Spot on!
